version: "3.5"

services:
  app:
    image: chess2:latest
    volumes:
      - ./config.json:/app/config/production.json
      - ${DATA_DIR}/chess2:/app/db
    networks:
      - traefik
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.chess2.entrypoints=https
      - traefik.http.routers.chess2.tls=true
      - traefik.http.routers.chess2.tls.certresolver=le
      - traefik.http.routers.chess2.rule=Host(`api.chess2online.com`)

networks:
  traefik:
    external: true
